// <auto-generated />
using System;
using Fleet.Server.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fleet.Server.Persistence.Migrations
{
    [DbContext(typeof(FleetDbContext))]
    [Migration("20260907204018_AddAuditEvents")]
    partial class AddAuditEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fleet.Server.Persistence.AssignmentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DesiredRevisionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolloutId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("TargetBase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DesiredRevisionId");

                    b.HasIndex("RolloutId", "Id");

                    b.HasIndex("NodeId", "TargetName", "IsCurrent")
                        .IsUnique()
                        .HasFilter("\"IsCurrent\"");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("Fleet.Server.Persistence.AssignmentSkillRow", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("BundleDigest")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.HasKey("AssignmentId", "Name");

                    b.HasIndex("BundleDigest");

                    b.ToTable("assignment_skills", (string)null);
                });

            modelBuilder.Entity("Fleet.Server.Persistence.AttemptRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Diagnostic")
                        .HasColumnType("text");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolloutId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("AssignmentId", "Id");

                    b.HasIndex("RolloutId", "Id");

                    b.ToTable("attempts", (string)null);
                });

            modelBuilder.Entity("Fleet.Server.Persistence.AuditEventRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "Id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Fleet.Server.Persistence.BundleRow", b =>
                {
                    b.Property<string>("Digest")
                        .HasColumnType("text");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Digest");

                    b.ToTable("bundles", (string)null);
                });

            modelBuilder.Entity("Fleet.Server.Persistence.CredentialRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CertificateSha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("NotAfter")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NotBefore")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CertificateSha256")
                        .IsUnique();

                    b.HasIndex("NodeId", "RevokedAt");

                    b.ToTable("node_credentials", (string)null);
                });

            modelBuilder.Entity("Fleet.Server.Persistence.DesiredRevisionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceRevision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "SourceRevision")
                        .IsUnique();

                    b.ToTable("desired_revisions", (string)null);
                });

            modelBuilder.Entity("Fleet.Server.Persistence.EnrollmentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CertificateRequestSha256")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("DeliveryPayload")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("RetryUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RetryWindowTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("TokenSha256")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenSha256")
                        .IsUnique();

                    b.HasIndex("WorkspaceId");

                    b.ToTable("enrollment_authorizations", (string)null);
                });

            modelBuilder.Entity("Fleet.Server.Persistence.NodeRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastContactAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "LastContactAt");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique();

                    b.ToTable("nodes", (string)null);
                });

            modelBuilder.Entity("Fleet.Server.Persistence.RolloutRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DesiredRevisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DesiredRevisionId");

                    b.ToTable("rollouts", (string)null);
                });

            modelBuilder.Entity("Fleet.Server.Persistence.SourceScanRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Diagnostic")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("text");

                    b.Property<string>("SourceRevision")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId", "ObservedAt");

                    b.ToTable("source_scans", (string)null);
                });

            modelBuilder.Entity("Fleet.Server.Persistence.WarningRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DesiredRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceLocations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("DesiredRevisionId");

                    b.ToTable("source_warnings", (string)null);
                });

            modelBuilder.Entity("Fleet.Server.Persistence.WorkspaceRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("Fleet.Server.Persistence.AssignmentRow", b =>
                {
                    b.HasOne("Fleet.Server.Persistence.DesiredRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("DesiredRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fleet.Server.Persistence.NodeRow", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fleet.Server.Persistence.RolloutRow", null)
                        .WithMany()
                        .HasForeignKey("RolloutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleet.Server.Persistence.AssignmentSkillRow", b =>
                {
                    b.HasOne("Fleet.Server.Persistence.AssignmentRow", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fleet.Server.Persistence.BundleRow", null)
                        .WithMany()
                        .HasForeignKey("BundleDigest")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleet.Server.Persistence.AttemptRow", b =>
                {
                    b.HasOne("Fleet.Server.Persistence.AssignmentRow", null)
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fleet.Server.Persistence.NodeRow", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fleet.Server.Persistence.RolloutRow", null)
                        .WithMany()
                        .HasForeignKey("RolloutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleet.Server.Persistence.AuditEventRow", b =>
                {
                    b.HasOne("Fleet.Server.Persistence.WorkspaceRow", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleet.Server.Persistence.CredentialRow", b =>
                {
                    b.HasOne("Fleet.Server.Persistence.NodeRow", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleet.Server.Persistence.DesiredRevisionRow", b =>
                {
                    b.HasOne("Fleet.Server.Persistence.WorkspaceRow", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleet.Server.Persistence.EnrollmentRow", b =>
                {
                    b.HasOne("Fleet.Server.Persistence.WorkspaceRow", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleet.Server.Persistence.NodeRow", b =>
                {
                    b.HasOne("Fleet.Server.Persistence.WorkspaceRow", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleet.Server.Persistence.RolloutRow", b =>
                {
                    b.HasOne("Fleet.Server.Persistence.DesiredRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("DesiredRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleet.Server.Persistence.SourceScanRow", b =>
                {
                    b.HasOne("Fleet.Server.Persistence.WorkspaceRow", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fleet.Server.Persistence.WarningRow", b =>
                {
                    b.HasOne("Fleet.Server.Persistence.DesiredRevisionRow", null)
                        .WithMany()
                        .HasForeignKey("DesiredRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
